name: Build and release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/workflow-build.yaml
  release:
    name: Release project packages
    runs-on: ubuntu-latest
    needs: build
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Create info file
        run: |
          echo "ref: ${GITHUB_REF}" > info.txt
          echo "commit: ${GITHUB_SHA}" >> info.txt
          echo "build: $(date +"%Y-%m-%dT%H:%M:%SZ")" >> info.txt
      - name: Publish release builds
        uses: ncipollo/release-action@v1
        with:
          artifacts: info.txt, ubuntu/openmsx-debugger-ubuntu-gh.tbz, macos/openmsx-debugger-macos-gh.tbz, mingw32/openmsx-debugger-mingw32-gh.zip
          body: "Build number ${{ github.run_number }}\n${{ github.event.head_commit.message }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          allowUpdates: true
